version: '3'

services:

  web:
    build: ./web
    container_name: web01
    networks:
      - nginx_network
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx01
    ports:
      - 80:80
    depends_on:
      - web
    environment:
      - "TZ=Japan"
    networks:
      - nginx_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx

networks:
  nginx_network:
    driver: bridge